# Form implementation generated from reading ui file 'lab2.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(899, 800)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(20, 20, 400, 400))
        self.image.setStyleSheet("background: gray;")
        self.image.setText("")
        self.image.setObjectName("image")
        self.file_browse = QtWidgets.QPushButton(Form)
        self.file_browse.setGeometry(QtCore.QRect(330, 440, 91, 23))
        self.file_browse.setObjectName("file_browse")
        self.filename_edit = QtWidgets.QLineEdit(Form)
        self.filename_edit.setGeometry(QtCore.QRect(20, 440, 301, 20))
        self.filename_edit.setObjectName("filename_edit")
        self.grayImage = QtWidgets.QLabel(Form)
        self.grayImage.setGeometry(QtCore.QRect(460, 20, 400, 400))
        self.grayImage.setStyleSheet("background: gray;")
        self.grayImage.setText("")
        self.grayImage.setObjectName("grayImage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_browse.setText(_translate("Form", "Загрузить"))
